# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/ssd1/2024/Huins-ssd1/easysoc-pynq/sogang/export/vivado_template_rev5/template/vivado/Example_Project/axi_mult_adder/axi_fnd_mult_adder/axi_fnd_mult_adder.srcs/sources_1/bd/design_1/ip/design_1_s_axi_template_0_0/design_1_s_axi_template_0_0.xci
# IP: The module: 'design_1_s_axi_template_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /mnt/ssd1/2024/Huins-ssd1/easysoc-pynq/sogang/export/vivado_template_rev5/template/vivado/Example_Project/axi_mult_adder/axi_fnd_mult_adder/axi_fnd_mult_adder.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xbip_multadd_0 || ORIG_REF_NAME==xbip_multadd_0} -quiet] -quiet

# XDC: /mnt/ssd1/2024/Huins-ssd1/easysoc-pynq/sogang/export/vivado_template_rev5/template/vivado/Example_Project/axi_mult_adder/axi_fnd_mult_adder/axi_fnd_mult_adder.gen/sources_1/bd/design_1/ip/design_1_s_axi_template_0_0/design_1_s_axi_template_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_s_axi_template_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/ssd1/2024/Huins-ssd1/easysoc-pynq/sogang/export/vivado_template_rev5/template/vivado/Example_Project/axi_mult_adder/axi_fnd_mult_adder/axi_fnd_mult_adder.srcs/sources_1/bd/design_1/ip/design_1_s_axi_template_0_0/design_1_s_axi_template_0_0.xci
# IP: The module: 'design_1_s_axi_template_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /mnt/ssd1/2024/Huins-ssd1/easysoc-pynq/sogang/export/vivado_template_rev5/template/vivado/Example_Project/axi_mult_adder/axi_fnd_mult_adder/axi_fnd_mult_adder.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xbip_multadd_0 || ORIG_REF_NAME==xbip_multadd_0} -quiet] -quiet

# XDC: /mnt/ssd1/2024/Huins-ssd1/easysoc-pynq/sogang/export/vivado_template_rev5/template/vivado/Example_Project/axi_mult_adder/axi_fnd_mult_adder/axi_fnd_mult_adder.gen/sources_1/bd/design_1/ip/design_1_s_axi_template_0_0/design_1_s_axi_template_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_s_axi_template_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
